const countryDifficulty = {
    "Afghanistan": "hard",
    "Albania": "hard",
    "Algeria": "hard",
    "Andorra": "hard",
    "Angola": "hard",
    "Argentina": "medium",
    "Armenia": "hard",
    "Australia": "easy",
    "Austria": "medium",
    "Azerbaijan": "hard",
    "Bahrain": "hard",
    "Bangladesh": "hard",
    "Barbados": "hard",
    "Belarus": "hard",
    "Belgium": "medium",
    "Belize": "hard",
    "Bhutan": "hard",
    "Bolivia": "hard",
    "Bosnia and Herzegovina": "hard",
    "Botswana": "hard",
    "Brazil": "easy",
    "Brunei": "hard",
    "Bulgaria": "hard",
    "Burkina Faso": "hard",
    "Burundi": "hard",
    "Cambodia": "hard",
    "Cameroon": "hard",
    "Canada": "easy",
    "Cape Verde": "hard",
    "Central African Republic": "hard",
    "Chad": "hard",
    "Chile": "medium",
    "Colombia": "medium",
    "Comoros": "hard",
    "Costa Rica": "medium",
    "Croatia": "hard",
    "Cuba": "medium",
    "Cyprus": "hard",
    "Czech Republic": "hard",
    "Democratic Republic of the Congo": "hard",
    "Denmark": "medium",
    "Djibouti": "hard",
    "Dominica": "hard",
    "Dominican Republic": "hard",
    "Ecuador": "hard",
    "Egypt": "easy",
    "El Salvador": "hard",
    "Equatorial Guinea": "hard",
    "Eritrea": "hard",
    "Estonia": "hard",
    "Eswatini": "hard",
    "Ethiopia": "hard",
    "Finland": "medium",
    "France": "easy",
    "Gabon": "hard",
    "Georgia": "hard",
    "Germany": "easy",
    "Ghana": "hard",
    "Greece": "easy",
    "Guatemala": "hard",
    "Guinea": "hard",
    "Guinea-Bissau": "hard",
    "Guyana": "hard",
    "Haiti": "hard",
    "Honduras": "hard",
    "Hungary": "hard",
    "Iceland": "medium",
    "India": "easy",
    "Indonesia": "medium",
    "Iran": "medium",
    "Iraq": "medium",
    "Ireland": "easy",
    "Israel": "easy",
    "Italy": "easy",
    "Ivory Coast": "hard",
    "Jamaica": "easy",
    "Japan": "easy",
    "Jordan": "hard",
    "Kazakhstan": "hard",
    "Kenya": "medium",
    "Kuwait": "hard",
    "Kyrgyzstan": "hard",
    "Latvia": "hard",
    "Lebanon": "hard",
    "Lesotho": "hard",
    "Liberia": "hard",
    "Libya": "hard",
    "Liechtenstein": "hard",
    "Lithuania": "hard",
    "Luxembourg": "hard",
    "Madagascar": "hard",
    "Malawi": "hard",
    "Malaysia": "medium",
    "Maldives": "medium",
    "Mali": "hard",
    "Mauritania": "hard",
    "Mauritius": "hard",
    "Mexico": "easy",
    "Moldova": "hard",
    "Monaco": "medium",
    "Mongolia": "hard",
    "Montenegro": "hard",
    "Morocco": "medium",
    "Mozambique": "hard",
    "Myanmar": "hard",
    "Namibia": "hard",
    "Nepal": "medium",
    "Netherlands": "medium",
    "New Zealand": "medium",
    "Nicaragua": "hard",
    "Niger": "hard",
    "Nigeria": "medium",
    "North Korea": "easy",
    "North Macedonia": "hard",
    "Norway": "medium",
    "Oman": "hard",
    "Pakistan": "medium",
    "Palau": "hard",
    "Palestine": "hard",
    "Panama": "medium",
    "Papua New Guinea": "hard",
    "Paraguay": "hard",
    "People's Republic of China": "easy",
    "Peru": "medium",
    "Philippines": "medium",
    "Poland": "medium",
    "Portugal": "medium",
    "Qatar": "hard",
    "Republic of the Congo": "hard",
    "Romania": "hard",
    "Russia": "easy",
    "Rwanda": "hard",
    "Saint Kitts and Nevis": "hard",
    "Saint Lucia": "hard",
    "Saint Vincent and the Grenadines": "hard",
    "Samoa": "hard",
    "San Marino": "hard",
    "Saudi Arabia": "easy",
    "Senegal": "hard",
    "Serbia": "hard",
    "Sierra Leone": "hard",
    "Singapore": "medium",
    "Slovakia": "hard",
    "Slovenia": "hard",
    "Solomon Islands": "hard",
    "Somalia": "hard",
    "Somaliland": "hard",
    "South Africa": "medium",
    "South Korea": "easy",
    "South Sudan": "hard",
    "Spain": "easy",
    "Sri Lanka": "hard",
    "Sudan": "hard",
    "Suriname": "hard",
    "Sweden": "medium",
    "Switzerland": "medium",
    "Syria": "hard",
    "São Tomé and Príncipe": "hard",
    "Taiwan": "medium",
    "Tajikistan": "hard",
    "Tanzania": "hard",
    "Thailand": "medium",
    "The Bahamas": "medium",
    "Timor-Leste": "hard",
    "Togo": "hard",
    "Tonga": "hard",
    "Trinidad and Tobago": "hard",
    "Tunisia": "hard",
    "Turkey": "easy",
    "Turkmenistan": "hard",
    "Tuvalu": "hard",
    "Uganda": "hard",
    "Ukraine": "easy",
    "United Arab Emirates": "medium",
    "United Kingdom": "easy",
    "United States": "easy",
    "Uruguay": "hard",
    "Uzbekistan": "hard",
    "Vanuatu": "hard",
    "Venezuela": "medium",
    "Vietnam": "medium",
    "Yemen": "hard",
    "Zambia": "hard",
    "Zimbabwe": "hard"
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = countryDifficulty;
}
